overrides:
- reason: "Cert-manager and its subcharts only runs on master nodes."
  rule: "PodHasArchBasedNodeAffinity"
  severity: "ERROR"
  reduceTo: "INFO"
- reason: "According to the ilmt page, IBM Cloud Private is not on the list to include metering annotations"
  rule : "MeteringAnnotationsDefined"
  severity: "ERROR"
  reduceTo: "INFO"
- reason: "The service account for the kube-system namespace created by ICP installer is named default"
  rule: "NoDefaultServiceAccountName"
  severity: "REVIEW"
  reduceTo: "INFO"
- reason: "All ICP platform services were instructed not to include the keyword Limited"
  rule: "ChartNameVersionClassificationMatch"
  message: ".* expected chart without name ending in \"-dev\" or \"-prod\" to have both the Commercial and Limited keywords"
  severity: "ERROR"
  reduceTo: "INFO"
- reason: "Having an application test will mess with the shared testing environment since we are a platform service."
  rule: "AppTestExists"
  severity: "ERROR"
  reduceTo: "INFO"
- reason: "This is not sensitive information, it's only what the pod can tolerate in an environment."
  rule: "NoSensitiveInfoInValues"
  message: ".* potentially secret parameter .*tolerations.*"
  severity: "REVIEW"
  reduceTo: "INFO"
- reason: "This doesn't have any value attached to it."
  rule: "NoSensitiveInfoInValues"
  message: ".* potentially secret parameter imagePullSecrets.*"
  severity: "REVIEW"
  reduceTo: "INFO"
- reason: "This is the first release of this product, so wouldn't the chart and app versions both be 1.0.0?"
  rule: "AppAndChartVersionsDoNotMatch"
  message: ".* appVersion and version both equal \"1.0.0\".*"
  severity: "REVIEW"
  reduceTo: "INFO"
- reason: "All ICP platform services were instructed not to include the keyword Limited"
  rule: "ChartNameVersionClassificationMatch"
  message: ".* expected chart .*"
  severity: "ERROR"
  reduceTo: "INFO"
- reason: "This service is not stateful and can come back up or be removed at any time without any disruption to the environment."
  rule: "PodDisruptionBudgetInReadme"
  severity: "WARNING"
  reduceTo: "INFO"
